require('dotenv').config();
var express=require('express');
var mongoose=require('mongoose');
var cors=require('cors');
var helmet=require('helmet');
var morgan=require('morgan');
var http=require('http');
var sio=require('socket.io');
var auth=require('./routes/auth');
var blocker=require('./routes/blocker');
var rules=require('./routes/rules');
var schedule=require('./routes/schedule');
var analytics=require('./routes/analytics');
var devices=require('./routes/devices');
var app=express();
var srv=http.createServer(app);
var io=new sio.Server(srv,{cors:{origin:'*'}});
app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(morgan('combined'));
app.use('/api/auth',auth);
app.use('/api/blocker',blocker);
app.use('/api/rules',rules);
app.use('/api/schedule',schedule);
app.use('/api/analytics',analytics);
app.use('/api/devices',devices);
app.get('/health',function(req,res){res.json({status:'OK'});});
app.use(function(req,res){res.status(404).json({error:'Not found'});});
io.on('connection',function(s){s.on('device:register',function(id){s.join('device:'+id);});});
app.set('io',io);
var PORT=process.env.PORT||3000;
var MONGO=process.env.MONGO_URI||'mongodb://localhost:27017/mana_blocker';
mongoose.connect(MONGO).then(function(){srv.listen(PORT,function(){console.log('Server running on port '+PORT);});}).catch(function(e){console.error(e.message);process.exit(1);});
